export default {
  login: 'john-smilga',
  id: 42133389,
  node_id: 'MDQ6VXNlcjQyMTMzMzg5',
  avatar_url: 'https://avatars3.githubusercontent.com/u/42133389?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/john-smilga',
  html_url: 'https://github.com/john-smilga',
  followers_url: 'https://api.github.com/users/john-smilga/followers',
  following_url:
    'https://api.github.com/users/john-smilga/following{/other_user}',
  gists_url: 'https://api.github.com/users/john-smilga/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/john-smilga/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/john-smilga/subscriptions',
  organizations_url: 'https://api.github.com/users/john-smilga/orgs',
  repos_url: 'https://api.github.com/users/john-smilga/repos',
  events_url: 'https://api.github.com/users/john-smilga/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/john-smilga/received_events',
  type: 'User',
  site_admin: false,
  name: 'John Smilga',
  company: 'Coding Addict',
  blog: 'www.johnsmilga.com',
  location: 'Los Angeles',
  email: null,
  hireable: null,
  bio: 'Creator of Coding Addict',
  twitter_username: 'john_smilga',
  public_repos: 152,
  public_gists: 0,
  followers: 1495,
  following: 0,
  created_at: '2018-08-06T06:48:23Z',
  updated_at: '2020-07-08T05:01:32Z',
};

//Bouchoucha Slim Data
/**
 * {
  "login": "SB-SLIM",
  "id": 3987392,
  "node_id": "MDQ6VXNlcjM5ODczOTI=",
  "avatar_url": "https://avatars.githubusercontent.com/u/3987392?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/SB-SLIM",
  "html_url": "https://github.com/SB-SLIM",
  "followers_url": "https://api.github.com/users/SB-SLIM/followers",
  "following_url": "https://api.github.com/users/SB-SLIM/following{/other_user}",
  "gists_url": "https://api.github.com/users/SB-SLIM/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/SB-SLIM/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/SB-SLIM/subscriptions",
  "organizations_url": "https://api.github.com/users/SB-SLIM/orgs",
  "repos_url": "https://api.github.com/users/SB-SLIM/repos",
  "events_url": "https://api.github.com/users/SB-SLIM/events{/privacy}",
  "received_events_url": "https://api.github.com/users/SB-SLIM/received_events",
  "type": "User",
  "site_admin": false,
  "name": "SLIM BOUCHOUCHA",
  "company": null,
  "blog": "",
  "location": null,
  "email": null,
  "hireable": null,
  "bio": null,
  "twitter_username": null,
  "public_repos": 7,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2013-03-27T17:23:04Z",
  "updated_at": "2021-12-27T14:02:18Z"
}
 */